# Generated by Django 4.1.7 on 2023-03-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='media/profile_avatar/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
