# Generated by Django 4.1.7 on 2023-03-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='profile_avatar/', verbose_name='avatar'),
        ),
    ]
