# Generated by Django 4.1.7 on 2023-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='dfaults/account_avatar.png', upload_to='profile_avatar/', verbose_name='avatar'),
        ),
    ]
