# Generated by Django 4.1.7 on 2023-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/account_avatar.png', upload_to='profile_avatar/', verbose_name='avatar'),
        ),
    ]
