# Generated by Django 4.1.7 on 2023-03-18 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('describtion', models.TextField(blank=True, verbose_name='describtion')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('exist_storeroom', models.PositiveSmallIntegerField(blank=True, verbose_name='exists in storeroom')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Producte',
                'verbose_name_plural': 'Productes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.TextField(verbose_name='describtion')),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='score')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producte', to='products.producte', verbose_name='describtion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvatarP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='media/product_avatar/%Y/%m/%d/', verbose_name='avatar')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productes', to='products.producte', verbose_name='producte')),
            ],
            options={
                'verbose_name': 'AvatarP',
                'verbose_name_plural': 'AvatarP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvatarC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='media/product_avatar/%Y/%m/%d/', verbose_name='avatar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'AvatarC',
                'verbose_name_plural': 'AvatarC',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
