# Generated by Django 4.1.7 on 2023-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarc',
            name='avatar',
            field=models.ImageField(upload_to='media/category_avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='avatarp',
            name='avatar',
            field=models.ImageField(upload_to='media/product_avatar/', verbose_name='avatar'),
        ),
    ]
