# Generated by Django 4.1.7 on 2023-03-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_avatarc_avatar_alter_avatarp_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarc',
            name='avatar',
            field=models.ImageField(upload_to='category_avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='avatarp',
            name='avatar',
            field=models.ImageField(upload_to='product_avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='describtion',
            field=models.TextField(blank=True, null=True, verbose_name='describtion'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='exist_storeroom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='exists in storeroom'),
        ),
    ]
