# Generated by Django 4.1.7 on 2023-03-22 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_avatarc_avatar_alter_avatarp_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='off',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='off'),
        ),
        migrations.AlterField(
            model_name='avatarc',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='avatarp',
            name='producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='products.producte', verbose_name='producte'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='products.producte', verbose_name='describtion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category', verbose_name='category'),
        ),
    ]
