# Generated by Django 4.1.7 on 2023-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producte_is_purchase_producte_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='pr_numbers',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='product numbers'),
        ),
    ]
