# Generated by Django 4.1.7 on 2023-04-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='is_purchase',
        ),
        migrations.AddField(
            model_name='producte',
            name='count',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='products.producte', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_purchase', models.BooleanField(verbose_name='purchase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='products.producte', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Buy',
                'verbose_name_plural': 'Buies',
                'managed': True,
            },
        ),
    ]
