# Generated by Django 4.1.7 on 2023-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_producte_is_purchase_producte_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='count'),
        ),
    ]
