# Generated by Django 4.1.7 on 2023-04-11 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_producte_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='expires_in',
            field=models.DurationField(default=datetime.timedelta(seconds=10)),
        ),
    ]
