# Generated by Django 4.1.7 on 2023-04-11 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_buy_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 0, 40, 39, 951965)),
        ),
    ]
