# Generated by Django 4.1.7 on 2023-04-11 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_buy_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 1, 5, 59, 352320)),
        ),
    ]
