# Generated by Django 4.1.7 on 2023-04-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_buy_created_at_alter_buy_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='expires_in',
        ),
    ]
